//-----------------------------------------------------------------------------
// Copyright (C) Proxmark3 contributors. See AUTHORS.md for details.
//
// This code is licensed to you under the terms of the GNU GPL, version 3 or,
// at your option, any later version. See the LICENSE.txt file for the text of
// the license.
//-----------------------------------------------------------------------------
// Version information on fpga images
//
// This file is generated by fpga_compress. Don't edit!
//-----------------------------------------------------------------------------


const int g_fpga_bitstream_num = 4;
const char *const g_fpga_version_information[4] = {
    " LF image 2s30vq100 2022-03-23 17:21:05",
    " HF image 2s30vq100 2022-03-23 17:21:16",
    " HF FeliCa image 2s30vq100 2022-03-23 17:21:27",
    " HF 15 image 2s30vq100 2022-03-23 17:21:38"
};
